#!/bin/bash
d=0;for((i=0;i<${#WATER};i++));do c=${WATER:i:1};case $c in w)v=0;;a)v=1;;t)v=2;;e)v=3;;r)v=4;;esac;d=$((d*5+v));done;e=0;for((i=0;i<${#STIR};i++));do c=${STIR:i:1};case $c in s)v=0;;t)v=1;;i)v=2;;r)v=3;;.)v=4;;esac;e=$((e*5+v));done;s=$((d+e));r="";b=bestchol;while((s>0));do r=${b:$((s%8)):1}$r;s=$((s/8));done;echo ${r:-b}
